### ISSUE TITLE
[FEATURE] - Adding log when running build

### ISSUE THREAD

**Issue by skylastn** [izzalDev/inno_build#49]
### Description

Adding Log when running dart run inno_build. it'll make the library more perfect 

### Motivation

i confuse what inno_build doing now, cause 50 minutes not done building apps

### Checklist

- [ ] I have checked the existing issues to see if this feature is already requested.
- [X] I have included a clear description and motivation for the feature.
- [ ] I have considered alternative solutions and provided context.

**Comment by skylastn** [comment]
![image](https://github.com/user-attachments/assets/ea3f5eae-fb04-4e92-b30e-0ab8826fc371)

**Comment by izzalDev** [comment]
Thank you for your feedback! I have added the improvement in version 0.3.0. You can update to this version and use the command `dart run inno_build --verbose` to display logs in the terminal. Please let me know if you encounter any errors.
